version: '3.8'
services:
  frontend:
    image: vijayvenkatj/campusconnect-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    
  backend:
    image: vijayvenkatj/campusconnect-backend:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - CLIENT_ID=${{ secrets.CLIENT_ID }}
      - CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
      - JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
      - DATABASE_URL=${{ secrets.DATABASE_URL }}
      - PORT=5000
      - REDIRECT_URL=http://127.0.0.1:5000/api/v1/user/oauth
      - BACKEND_URL=http://localhost:5000
      - FRONTEND_URL=http://localhost:5173
      - BUCKET_NAME=${{ secrets.BUCKET_NAME }}
      - AWS_REGION=${{ secrets.AWS_REGION }}
      - AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
