version: '3.8'
services:
  frontend:
    image: vijayvenkatj/campusconnect-frontend:1.0
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    
  backend:
    image: vijayvenkatj/campusconnect-backend:1.1
    restart: always
    ports:
      - "5000:5000"
